---
- hosts: db
  become: yes
  gather_facts: 1
  ignore_errors: yes
  tasks:
    - name: check number of cpu
      command: nproc
      register: nproc_output

    - name: display the output
      debug:
        var: nproc_output.stdout

    - name: create file
      file:
        path: /home/ec2-user/week3
        state: touch
        mode: '0644'
      register: file_output

    - name: display output
      debug:
        var: file_output

    